server:
  port: 80
spring:
  application:
    name: cloud-consumer-openfight-order
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
ribbon:
  ReadTimeout:  5000 # 读取有效时长
  ConnectTimeout: 5000 # 链接时长
logging:
  level:
    cn.aokan.service.PaymentService: debug

 
